"""baseline: adopt existing schema

Revision ID: 95d4c8726a1b
Revises: 
Create Date: 2026-08-16 13:54:33.290995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95d4c8726a1b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Deliberately empty.

    The schema this project runs on was built by metadata.create_all plus
    the hand-written ALTERs in app/database.py, and it already exists in
    production. This revision exists only to be stamped, so Alembic has a
    starting point to measure future changes from.

    It must stay empty. An autogenerated baseline was tried first and came
    back proposing to DROP columns the live database has but the models do
    not (classes.position, classes.weekly_schedule, device_tokens.student_id)
    -- running that would have destroyed real data. Reconciling that drift
    is a separate, deliberate job, not something a baseline should do
    silently.
    """
    pass
    """Upgrade schema."""
    pass


def downgrade() -> None:
    """Nothing to undo -- see upgrade()."""
    pass
    """Downgrade schema."""
    pass
